### ISSUE TITLE
Can you massage joints to break down crystals?

### ISSUE THREAD

**Issue by KeithCharlieTaylor** [kct2020/goutpal-com-skeleventy#67] opened 2022-03-11 17:45 UTC
Page URL: https://www.goutpal.com/gout-pal-forum/please-help-my-gout/can-you-massage-your-joint-to-break-down-crystals/

Page Title: Can you massage joints to break down crystals?

Page Description: 30 Sept 2008 ... Can you massage gout crystals away? Massage has its place in gout relief. But the wrong type of massage does more harm than good.

## Additional context ##
High interest in many concerns about massaging and gout.

**Comment by kct2020** [comment] 2022-04-26 02:34
Duplicate of #86

**Closed by kct2020** 2022-04-26 02:34 UTC
Labels: Waiting Comment, High Interest
